language: go

go:
  - "1.14.x"
  - master

git:
  quiet: true

matrix:
  # Build OK if fails on unstable development versions of Go.
  allow_failures:
    - go: master
  # Don't wait for tests to finish on allow_failures.
  # Mark the build finished if tests pass on other versions of Go.
  fast_finish: true

addons:
    mariadb: "10.3"

go_import_path: github.com/wasabee-project/Wasabee-Server

before_install:
     - echo "CREATE DATABASE wasabee" | mysql -u root --password="" 

install:
    # - go get -t -v $(go list ./... | grep -v integration)
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - go build -v ./...
    - go install -v ./...

script:
    - ls $GOPATH/bin
    #- go test -v -race -test.short ./...        # Run tests with the race detector.
    # - go get -v ./...                           # Run Go static analyzer.
    #- go test -v -covermode=count -coverprofile=coverage.out
    - wasabee-userupdate
    #- goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
