language: go

go:
  - "1.12.x"
  - master

git:
  quiet: true

matrix:
  # Build OK if fails on unstable development versions of Go.
  allow_failures:
    - go: master
  # Don't wait for tests to finish on allow_failures.
  # Mark the build finished if tests pass on other versions of Go.
  fast_finish: true

addons:
    mariadb: "10.3"

go_import_path: github.com/cloudkucooland/WASABI

before_install:
     - echo "CREATE DATABASE wasabi" | mysql -u root --password="" 

install:
    - go get -t -v $(go list ./... | grep -v integration)
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - go install -v ./...

script:
    #- go test -v -race -test.short ./...        # Run tests with the race detector.
    - go get -v ./...                           # Run Go static analyzer.
    - go test -v -covermode=count -coverprofile=coverage.out
    - $HOME/gopath/bin/wasabi-userupdate
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
